<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Expense;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LegacyExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $charges = [
            [
                'id' => 16,
                'amount' => 70000.00,
                'date' => '2023-09-22',
                'description' => 'Hotel +',
                'mission_id' => 271,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-12 05:30:32',
                'updated_at' => '2026-05-12 05:30:32',
            ],
            [
                'id' => 17,
                'amount' => 70000.00,
                'date' => '2024-05-11',
                'description' => 'Hotel +',
                'mission_id' => 273,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-12 05:40:47',
                'updated_at' => '2026-05-12 05:40:47',
            ],
            [
                'id' => 18,
                'amount' => 70000.00,
                'date' => '2024-10-27',
                'description' => 'Hotel +',
                'mission_id' => 274,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-12 06:10:36',
                'updated_at' => '2026-05-12 06:10:36',
            ],
            [
                'id' => 19,
                'amount' => 70000.00,
                'date' => '2025-04-29',
                'description' => 'Hotel +',
                'mission_id' => 275,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-12 06:19:35',
                'updated_at' => '2026-05-12 06:19:45',
            ],
            [
                'id' => 20,
                'amount' => 74935.00,
                'date' => '2025-10-28',
                'description' => 'Hotel +',
                'mission_id' => 168,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-12 06:23:43',
                'updated_at' => '2026-05-12 06:23:43',
            ],
            [
                'id' => 21,
                'amount' => 40345.00,
                'date' => '2026-04-08',
                'description' => 'Hotel +',
                'mission_id' => 259,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-12 06:31:52',
                'updated_at' => '2026-05-12 06:31:52',
            ],
            [
                'id' => 22,
                'amount' => 70000.00,
                'date' => '2024-06-09',
                'description' => 'Hotel +',
                'mission_id' => 279,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-13 08:48:56',
                'updated_at' => '2026-05-13 08:48:56',
            ],
            [
                'id' => 23,
                'amount' => 70000.00,
                'date' => '2025-08-09',
                'description' => 'Hotel +',
                'mission_id' => 282,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-13 09:06:39',
                'updated_at' => '2026-05-13 09:07:05',
            ],
            [
                'id' => 24,
                'amount' => 95000.00,
                'date' => '2025-11-15',
                'description' => 'Hotel +',
                'mission_id' => 283,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-13 09:13:09',
                'updated_at' => '2026-05-13 09:13:09',
            ],
            [
                'id' => 25,
                'amount' => 5015.54,
                'date' => '2026-05-13',
                'description' => 'Facture Sonelgaz',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-05-13 10:47:52',
                'updated_at' => '2026-05-13 10:47:52',
            ],
            [
                'id' => 26,
                'amount' => 3570.00,
                'date' => '2026-05-13',
                'description' => 'Facture Yalidine',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-05-13 10:48:35',
                'updated_at' => '2026-05-13 10:48:35',
            ],
            [
                'id' => 27,
                'amount' => 7520.00,
                'date' => '2026-05-13',
                'description' => 'Facture Vol Raouf',
                'mission_id' => 276,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-05-13 11:09:07',
                'updated_at' => '2026-05-13 11:09:07',
            ],
            [
                'id' => 28,
                'amount' => 9130.00,
                'date' => '2026-05-13',
                'description' => 'Poubelles Classeurs flash disques soumission GTIM',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-05-14 06:32:07',
                'updated_at' => '2026-05-14 06:32:07',
            ],
            [
                'id' => 29,
                'amount' => 53650.00,
                'date' => '2026-05-23',
                'description' => 'Mob / Demob TNK',
                'mission_id' => 277,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-06-01 07:29:44',
                'updated_at' => '2026-06-01 07:29:44',
            ],
            [
                'id' => 31,
                'amount' => 2295.47,
                'date' => '2026-06-01',
                'description' => 'DHL-5111810841',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-06-01 10:49:02',
                'updated_at' => '2026-06-01 10:49:02',
            ],
            [
                'id' => 32,
                'amount' => 3850.00,
                'date' => '2026-06-03',
                'description' => 'Multiprises  BMX 5M',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-06-03 10:48:03',
                'updated_at' => '2026-06-03 10:48:03',
            ],
            [
                'id' => 33,
                'amount' => 707098.00,
                'date' => '2026-06-04',
                'description' => 'Etalonnage lot 1 Reel services',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'fixed',
                'created_at' => '2026-06-04 06:46:08',
                'updated_at' => '2026-06-04 06:46:08',
            ],
            [
                'id' => 34,
                'amount' => 7476500.00,
                'date' => '2026-01-01',
                'description' => 'Salaires, Comptabilité, services',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'fixed',
                'created_at' => '2026-06-04 11:06:21',
                'updated_at' => '2026-06-04 11:06:21',
            ],
            [
                'id' => 35,
                'amount' => 13400.00,
                'date' => '2026-07-02',
                'description' => 'Internet',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'fixed',
                'created_at' => '2026-07-02 08:31:20',
                'updated_at' => '2026-07-02 08:31:20',
            ],
            [
                'id' => 36,
                'amount' => 600.00,
                'date' => '2026-07-02',
                'description' => 'Telephone fix',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'fixed',
                'created_at' => '2026-07-02 08:31:40',
                'updated_at' => '2026-07-02 08:31:40',
            ],
            [
                'id' => 37,
                'amount' => 19960.00,
                'date' => '2026-06-20',
                'description' => 'mob-Stah',
                'mission_id' => 287,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-07-13 13:50:26',
                'updated_at' => '2026-07-13 13:50:26',
            ],
            [
                'id' => 38,
                'amount' => 23260.00,
                'date' => '2026-07-16',
                'description' => 'Dmob-GTFT',
                'mission_id' => 288,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-07-18 20:48:03',
                'updated_at' => '2026-07-18 20:48:24',
            ],
            [
                'id' => 39,
                'amount' => 1190.56,
                'date' => '2026-07-20',
                'description' => 'Electricité Cité cilla',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 07:11:14',
                'updated_at' => '2026-07-20 07:11:14',
            ],
            [
                'id' => 40,
                'amount' => 7905.00,
                'date' => '2026-07-13',
                'description' => 'Frais dossier AO GBRS',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 07:13:05',
                'updated_at' => '2026-07-20 07:13:05',
            ],
            [
                'id' => 41,
                'amount' => 1900.00,
                'date' => '2026-07-20',
                'description' => 'Frais dossier AO GRN',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 07:18:04',
                'updated_at' => '2026-07-20 07:18:04',
            ],
            [
                'id' => 42,
                'amount' => 3700.00,
                'date' => '2026-07-16',
                'description' => 'Frais dossier AO GBRS DHL',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 07:18:37',
                'updated_at' => '2026-07-20 07:18:37',
            ],
            [
                'id' => 43,
                'amount' => 2300.00,
                'date' => '2026-07-16',
                'description' => 'DHL',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'prisma',
                'charge_type' => null,
                'created_at' => '2026-07-20 07:19:25',
                'updated_at' => '2026-07-20 07:19:25',
            ],
            [
                'id' => 44,
                'amount' => 3000.00,
                'date' => '2026-07-09',
                'description' => 'Netoyage bureau',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 07:20:28',
                'updated_at' => '2026-07-20 07:20:28',
            ],
            [
                'id' => 45,
                'amount' => 3500.00,
                'date' => '2026-07-12',
                'description' => 'Café + eau',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 07:20:59',
                'updated_at' => '2026-07-20 07:20:59',
            ],
            [
                'id' => 46,
                'amount' => 3000.00,
                'date' => '2026-07-20',
                'description' => 'Frais dossier AO GRN',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-20 08:59:13',
                'updated_at' => '2026-07-20 08:59:13',
            ],
            [
                'id' => 47,
                'amount' => 1500.00,
                'date' => '2026-07-20',
                'description' => 'Grapheuse bois',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-21 09:22:01',
                'updated_at' => '2026-07-21 09:22:01',
            ],
            [
                'id' => 48,
                'amount' => 650.00,
                'date' => '2026-07-23',
                'description' => 'teflon divers',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-26 07:19:09',
                'updated_at' => '2026-07-26 07:19:09',
            ],
            [
                'id' => 49,
                'amount' => 400.00,
                'date' => '2026-07-23',
                'description' => 'Metre à ruban',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-26 07:20:07',
                'updated_at' => '2026-07-26 07:20:07',
            ],
            [
                'id' => 50,
                'amount' => 2650.00,
                'date' => '2026-07-25',
                'description' => 'Mob / Demob STAH Jauge',
                'mission_id' => 282,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-07-26 07:23:48',
                'updated_at' => '2026-07-29 16:12:54',
            ],
            [
                'id' => 51,
                'amount' => 35000.00,
                'date' => '2026-07-22',
                'description' => 'Compresseur',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-26 08:57:47',
                'updated_at' => '2026-07-26 08:57:47',
            ],
            [
                'id' => 52,
                'amount' => 200.00,
                'date' => '2026-07-27',
                'description' => 'joints raccords',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-27 08:06:23',
                'updated_at' => '2026-07-27 08:06:23',
            ],
            [
                'id' => 53,
                'amount' => 210.00,
                'date' => '2026-07-27',
                'description' => 'eau',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-27 09:08:19',
                'updated_at' => '2026-07-27 09:08:19',
            ],
            [
                'id' => 54,
                'amount' => 4522.00,
                'date' => '2026-07-27',
                'description' => 'Software OFFICE 2019 x 2',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-07-27 09:18:02',
                'updated_at' => '2026-07-27 09:18:02',
            ],
            [
                'id' => 55,
                'amount' => 2600.00,
                'date' => '2026-08-01',
                'description' => 'Mob / Demob',
                'mission_id' => 291,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'mission',
                'charge_type' => null,
                'created_at' => '2026-08-03 09:25:03',
                'updated_at' => '2026-08-03 09:25:12',
            ],
            [
                'id' => 56,
                'amount' => 1000.00,
                'date' => '2026-08-04',
                'description' => 'Taxi-Doc-oran',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-04 10:37:34',
                'updated_at' => '2026-08-04 10:37:34',
            ],
            [
                'id' => 57,
                'amount' => 3400.00,
                'date' => '2026-08-05',
                'description' => 'Accessoire- Cache Modem',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-05 10:17:48',
                'updated_at' => '2026-08-05 10:17:48',
            ],
            [
                'id' => 58,
                'amount' => 3000.00,
                'date' => '2026-08-06',
                'description' => 'Papier A4',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-06 10:21:03',
                'updated_at' => '2026-08-06 10:21:03',
            ],
            [
                'id' => 59,
                'amount' => 3452.55,
                'date' => '2026-08-11',
                'description' => 'Facture Sonelgaz',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-10 12:02:21',
                'updated_at' => '2026-08-11 07:23:11',
            ],
            [
                'id' => 60,
                'amount' => 98175.00,
                'date' => '2026-05-02',
                'description' => 'Imprimante GX3040 + Toner MF550',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-11 07:26:01',
                'updated_at' => '2026-08-11 07:26:01',
            ],
            [
                'id' => 61,
                'amount' => 87900.00,
                'date' => '2026-05-04',
                'description' => 'Imprimante Portable BX110',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-11 07:30:06',
                'updated_at' => '2026-08-11 07:30:06',
            ],
            [
                'id' => 62,
                'amount' => 1712.00,
                'date' => '2026-08-11',
                'description' => 'Facture Seaal',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-11 10:03:57',
                'updated_at' => '2026-08-11 10:03:57',
            ],
            [
                'id' => 63,
                'amount' => 400.00,
                'date' => '2026-08-18',
                'description' => 'Outillage les attaches',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-18 09:04:00',
                'updated_at' => '2026-08-18 09:04:00',
            ],
            [
                'id' => 64,
                'amount' => 3200.00,
                'date' => '2026-08-18',
                'description' => 'Boites de rangement',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-08-18 10:22:34',
                'updated_at' => '2026-08-18 10:22:34',
            ],
            [
                'id' => 65,
                'amount' => 200.00,
                'date' => '2026-09-02',
                'description' => 'Savon  liquide',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-09-02 18:54:40',
                'updated_at' => '2026-09-02 18:54:40',
            ],
            [
                'id' => 66,
                'amount' => 1300.00,
                'date' => '2026-09-06',
                'description' => 'USB-Drive',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-09-06 10:43:13',
                'updated_at' => '2026-09-06 10:43:13',
            ],
            [
                'id' => 67,
                'amount' => 240000.00,
                'date' => '2026-09-13',
                'description' => 'NAPEC Costumes',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-09-13 08:40:38',
                'updated_at' => '2026-09-13 08:40:38',
            ],
            [
                'id' => 68,
                'amount' => 892500.00,
                'date' => '2026-04-30',
                'description' => 'NAPEC Inscription Stand',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-09-13 08:43:35',
                'updated_at' => '2026-09-13 08:43:35',
            ],
            [
                'id' => 69,
                'amount' => 297500.00,
                'date' => '2026-07-12',
                'description' => 'NAPEC Inscription Co exposant',
                'mission_id' => null,
                'contract_id' => null,
                'attachment_item_id' => null,
                'item_type_id' => null,
                'type' => 'gmtm',
                'charge_type' => 'variable',
                'created_at' => '2026-09-13 08:45:05',
                'updated_at' => '2026-09-13 08:45:05',
            ],
        ];

        DB::transaction(function () use ($charges): void {
            foreach ($charges as $charge) {
                Expense::updateOrCreate(['id' => $charge['id']], $charge);
            }
        });
    }
}
